cc_test(
    name = "test_bme280_cpp_driver",
    srcs = ["test_bme280_cpp_driver.cpp"],
    deps = [
        "//src/cpp_driver:bme280_cpp_driver",
        "@com_google_googletest//:gtest",
        "@com_google_googletest//:gtest_main",
    ],
)