py_binary(
    name = "main",
    srcs = ["main.py"],
    deps = [
        ":db_handler",
    ]
)

py_binary(
    name = "flask_web_app",
    srcs = ["flask_web_app.py"],
    deps = [],
)

py_library(
    name = "db_handler",
    srcs = ["db_handler.py"],
)

